const seedExpenses=[{name:'Coffee',amount:4500,category:'Food',date:'Today'},{name:'Groceries',amount:68200,category:'Home',date:'Yesterday'},{name:'Taxi',amount:12000,category:'Travel',date:'Tue'},{name:'Dinner',amount:31400,category:'Food',date:'Mon'}];
const palette={Food:'#bf805d',Home:'#8da27f',Travel:'#9bc9d9',Other:'#cda572'};const formatter=new Intl.NumberFormat('en-UG');let expenses=JSON.parse(localStorage.getItem('morrow-expenses')||'null')||seedExpenses;let activeCategory='Travel';
const amount=document.querySelector('#amount'),note=document.querySelector('#note');const shillings=value=>`USh ${formatter.format(value)}`;
function escapeHtml(value){const el=document.createElement('div');el.textContent=value;return el.innerHTML}
function render(){const total=expenses.reduce((sum,item)=>sum+item.amount,0);document.querySelector('#total').textContent=shillings(total);document.querySelector('#expense-count').textContent=`${expenses.length} ${expenses.length===1?'entry':'entries'} this month`;document.querySelector('#weekly-total').textContent=shillings(expenses.slice(0,4).reduce((sum,item)=>sum+item.amount,0));const itemHtml=item=>`<div class="expense"><span class="dot" style="background:${palette[item.category]}"></span><span class="expense-name">${escapeHtml(item.name)}<small>${item.date}</small></span><span class="expense-category">${item.category}</span><span class="expense-cost">${shillings(item.amount)}</span></div>`;document.querySelector('#recent-list').innerHTML=expenses.slice(0,3).map(itemHtml).join('');document.querySelector('#expense-list').innerHTML=expenses.map(itemHtml).join('');renderWeeklyChart();renderBreakdown()}
function renderWeeklyChart(){const points=[42000,58000,47000,89000,64000,108000,76000],max=Math.max(...points),width=480,height=196;const coords=points.map((value,index)=>`${index*(width/6)},${height-(value/max)*156}`).join(' ');const area=`0,${height} ${coords} ${width},${height}`;document.querySelector('#weekly-chart').innerHTML=`<path d="M ${area.replaceAll(' ',' L ')} Z" fill="#d9eaed"></path><polyline points="${coords}" fill="none" stroke="#72a9ba" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"></polyline><circle cx="400" cy="40" r="8" fill="#bf805d"></circle>`}
function renderBreakdown(){const totals=Object.keys(palette).map(category=>({category,value:expenses.filter(item=>item.category===category).reduce((sum,item)=>sum+item.amount,0)})),max=Math.max(...totals.map(item=>item.value),1);document.querySelector('#breakdown-chart').innerHTML=totals.map(item=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(8,item.value/max*185)}px;background:${palette[item.category]}"></div><small>${item.category}</small><b>${item.value?shillings(item.value):'—'}</b></div>`).join('')}
function goTo(page){document.querySelectorAll('.page').forEach(section=>section.classList.toggle('active',section.id===`${page}-page`));document.querySelectorAll('.nav-link').forEach(button=>button.classList.toggle('active',button.dataset.page===page));const titles={home:['Good afternoon','SEPTEMBER 2026'],expenses:['Your expenses','MORROW'],insights:['Your spending','MORROW']};document.querySelector('#page-title').textContent=titles[page][0];document.querySelector('#page-kicker').textContent=titles[page][1]}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelector('#login-form').addEventListener('submit',event=>{event.preventDefault();sessionStorage.setItem('morrow-signed-in','true');document.querySelector('#login-view').classList.add('hidden');document.querySelector('#app-view').classList.remove('hidden');render()});document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>goTo(button.dataset.page)));document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>goTo(button.dataset.go)));document.querySelector('#category-picker').addEventListener('click',event=>{if(!event.target.matches('button'))return;activeCategory=event.target.dataset.category;document.querySelectorAll('#category-picker button').forEach(button=>button.classList.toggle('selected',button===event.target))});document.querySelector('#save-expense').addEventListener('click',()=>{const value=Number(amount.value.replace(/\D/g,'')),description=note.value.trim();if(!value||!description)return showToast('Add an amount and a note first.');expenses.unshift({name:description,amount:value,category:activeCategory,date:'Today'});localStorage.setItem('morrow-expenses',JSON.stringify(expenses));amount.value='';note.value='';render();showToast('Expense saved.')});document.querySelector('#sign-out').addEventListener('click',()=>{sessionStorage.removeItem('morrow-signed-in');document.querySelector('#app-view').classList.add('hidden');document.querySelector('#login-view').classList.remove('hidden');document.querySelector('#login-form').reset()});if(sessionStorage.getItem('morrow-signed-in')){document.querySelector('#login-view').classList.add('hidden');document.querySelector('#app-view').classList.remove('hidden');render()}
